### ISSUE TITLE
Quick notes about quick rsqrt

### ISSUE THREAD

**Issue by MaxGraey** [YuriyVorobyov96/asm-script-fast-inv-sqrt#1]
Hi! You can use built-in `reinterpret` op instead suboptimal conv via typed array for such purposes. For example, Quake's `rsqrt` can be represented as:
```ts
function rsqrtQuick(x: f32): f32 {
  let y = x;
  let u = reinterpret<u32>(y);
  u = 0x5F3759DF - (u >> 1);
  y = reinterpret<f32>(u);
  y *= 1.5 - (0.5 * x) * y * y; // 1st Newton's iter
  // y *= 1.5 - (0.5 * x) * y * y; // 2nd Newton's iter
  return y;
}
```

But in modern CPUs it doesn't make sense for a while now. Since the speed is much lower than native `1 / sqrt(x)`, and the accuracy is incomparably lower.

See simple benchmark on [playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY29uc3QgTiA9IDEwXzAwMF8wMDA7CmNvbnN0IGludk4gPSAxLjAgLyBmNjQoTik7CgpleHBvcnQgZnVuY3Rpb24gYmVuY2hfcnNxcnRRdWljaygpOiBmNjQgewogIGxldCBzdW0gPSAwLjA7CiAgZm9yIChsZXQgaSA9IDA7IGkgPCBOOyBpKyspIHsKICAgIHN1bSArPSByc3FydFF1aWNrKGkgYXMgZjMyKSBhcyBmNjQgKiBpbnZOOwogIH0KICByZXR1cm4gc3VtOwp9CgpleHBvcnQgZnVuY3Rpb24gYmVuY2hfcnNxcnRQcmVjKCk6IGY2NCB7CiAgbGV0IHN1bSA9IDAuMDsKICBmb3IgKGxldCBpID0gMDsgaSA8IE47IGkrKykgewogICAgc3VtICs9IHJzcXJ0UHJlYyhpIGFzIGYzMikgYXMgZjY0ICogaW52TjsKICB9CiAgcmV0dXJuIHN1bTsKfQoKZXhwb3J0IGZ1bmN0aW9uIGJlbmNoX3JzcXJ0KCk6IGY2NCB7CiAgbGV0IHN1bSA9IDAuMDsKICBmb3IgKGxldCBpID0gMDsgaSA8IE47IGkrKykgewogICAgc3VtICs9IHJzcXJ0KGkgYXMgZjMyKSBhcyBmNjQgKiBpbnZOOwogIH0KICByZXR1cm4gc3VtOwp9CgoKZnVuY3Rpb24gcnNxcnRRdWljayh4OiBmMzIpOiBmMzIgewoJbGV0IHkgPSB4OwoJbGV0IHUgPSByZWludGVycHJldDx1MzI+KHkpOwoJdSA9IDB4NUYzNzU5REYgLSAodSA+PiAxKTsKCXkgPSByZWludGVycHJldDxmMzI+KHUpOwoJeSA9IHkgKiAoMS41IC0gKDAuNSAqIHgpICogeSAqIHkpOyAvLyAxc3QgTmV3dG9uJ3MgaXRlcgoJcmV0dXJuIHk7Cn0KCmZ1bmN0aW9uIHJzcXJ0UHJlYyh4OiBmMzIpOiBmMzIgewoJbGV0IHkgPSB4OwoJbGV0IHUgPSByZWludGVycHJldDx1MzI+KHkpOwoJdSA9IDB4NUYzNzU5REYgLSAodSA+PiAxKTsKCXkgPSByZWludGVycHJldDxmMzI+KHUpOwoJeSA9IHkgKiAoMS41IC0gKDAuNSAqIHgpICogeSAqIHkpOyAvLyAxc3QgTmV3dG9uJ3MgaXRlcgogIHkgPSB5ICogKDEuNSAtICgwLjUgKiB4KSAqIHkgKiB5KTsgLy8gMm5kIE5ld3RvbidzIGl0ZXIKCXJldHVybiB5Owp9CgpmdW5jdGlvbiByc3FydCh4OiBmMzIpOiBmMzIgewogIHJldHVybiAxLjAgLyBNYXRoZi5zcXJ0KHgpOwp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQgdHlwZT0ibW9kdWxlIj4KY29uc3QgZXhwb3J0cyA9IGF3YWl0IGluc3RhbnRpYXRlKGF3YWl0IGNvbXBpbGUoKSwgeyAvKiBpbXBvcnRzICovIH0pCmNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQpjb25zdCB7IGJlbmNoX3JzcXJ0UXVpY2ssIGJlbmNoX3JzcXJ0UHJlYywgYmVuY2hfcnNxcnQgfSA9IGV4cG9ydHMKCmZ1bmN0aW9uIGJlbmNoKGZuLCBuYW1lKSB7CiAgLy8gd2FybXVwCiAgZm9yIChsZXQgaSA9IDA7IGkgPCA0MDsgaSsrKSB7CiAgICBmbigpOwogIH0KCiAgbGV0IHQgPSBwZXJmb3JtYW5jZS5ub3coKTsKICBsZXQgcmVzID0gZm4oKTsKICB0ID0gcGVyZm9ybWFuY2Uubm93KCkgLSB0OwogIG91dHB1dC52YWx1ZSArPSBgJHtuYW1lfTpcbiAtIFRpbWU6ICR7dC50b0ZpeGVkKDMpfSBtc1xuIC0gQWNjUHJlYzogJHtyZXN9XG5cbmA7Cn0KCmJlbmNoKGJlbmNoX3JzcXJ0LCAiMSAvIHNxcnQoeCkiKQpiZW5jaChiZW5jaF9yc3FydFF1aWNrLCAiUXVha2UncyByc3FydCAoMSBpdGVyKSIpCmJlbmNoKGJlbmNoX3JzcXJ0UHJlYywgIlF1YWtlJ3MgcnNxcnQgKDIgaXRlcnMpIikKPC9zY3JpcHQ+)

Results for Chrome:
```
1 / sqrt(x):
 - Time: 14.900 ms
 - AccPrec: Infinity

Quake's rsqrt (1 iter):
 - Time: 17.200 ms
 - AccPrec: 1981775370968.5767

Quake's rsqrt (2 iters):
 - Time: 25.300 ms
 - AccPrec: 2972662946501.702
```

**Comment by YuriyVorobyov96** [comment]
Hi @MaxGraey!
Thank you for info about `reinterpret`, I missed it!

I know about the speed in modern CPUs and the accuracy problems, I just came across the AssemblyScript for the first time, and the first thing that came to mind for implementation was a fast inverse square root.

**Comment by MaxGraey** [comment]
I see. Btw, a full list of built-in low level instructions you can find here:
https://www.assemblyscript.org/stdlib/globals.html#webassembly
